server {
    listen 80;
    server_name 100.49.172.129;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 100.49.172.129;

    ssl_certificate /etc/letsencrypt/live/100.49.172.129/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/100.49.172.129/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_ciphers 'HIGH:!aNULL:!MD5';

    ssl_prefer_server_ciphers off;

    root /usr/share/nginx/html;
    index index.html;

    # ==========================================
    # HEALTH CHECK
    # ==========================================
    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }

    # ==========================================
    # ANGULAR SPA
    # ==========================================
    location / {
        try_files $uri $uri/ /index.html;
    }
}