server {
    listen 80;
    server_name 100.49.172.129;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://100.49.172.129$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 100.49.172.129;
    
    ssl_certificate /etc/letsencrypt/live/100.49.172.129/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/100.49.172.129/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_session_tickets off;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Permite abrir directamente las rutas de Angular, incluido /catalog.
        try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache";
    }
    
    # Caché opcional para archivos estáticos de assets
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
